@testable import TestingWildcards

// could I make my own protocol based on CaseIterable but which adds iterable over
// associated types that are CaseIterable?
enum Mode: CaseIterable, InvariantValues, CustomStringConvertible {
//    case alpha, beta, gamma(Bool)
    case alpha, beta, gamma

    var description: String {
        switch self {
        case .alpha: return "Alpha"
        case .beta: return "Beta"
        case .gamma: return "Gamma"
        }
    }
}

struct FilePermission: OptionSet {
    let rawValue: Int

    static let read    = FilePermission(rawValue: 1 << 0)
    static let write   = FilePermission(rawValue: 1 << 1)
    static let execute = FilePermission(rawValue: 1 << 2)

    static let all: FilePermission = [.read, .write, .execute]
}

struct Example: WildcardPrototyping, CustomStringConvertible {
    public static var prototype: Self {
        .init()
    }

//    public init() { }

    // recommended pattern -- set all properties values to default, then prototype can just call the autogenerated .init()
    var name: String = "bob"
    var flag: Bool = false
    var mode: Mode = .alpha
    var count: Int = 0
    var a: Int = 0
    var b: Int = 0
    var c: Int = 0
    var filePermission: FilePermission = .all
    var error: SomeError? = nil


    var description: String {
        "[Example name: \(name) flag: \(flag), mode: \(mode), count: \(count), abc: \(a) \(b) \(c) error: \(String(describing: error))])"
    }

//    public static func callAsFunction(_ wildcardPaths: [WildcardPath<Self>]) -> [Self] {
//        TestingWildcards.allInvariantCombinations(Self.prototype, wildcardPaths: wildcardPaths)
//    }

}

enum SomeError: Error, InvariantValues, CaseIterable {
    case catWokeUp
    case dogGotRainedOn
}
